config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :sources
  resources :libraries
  resources :playlists do
    resources :playlist_tracks
    resources :tracks, only: [:new, :create]
  end
  resources :playlist_tracks
  resources :tracks do 
    member do
      get 'play_previous'
      get 'play_next'
    end
  end
  root 'home#index'
  get 'search_type', to: 'home#search_type', as: :search_type
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/inbox"
end

app/models/track.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tracks
#
#  id          :bigint(8)        not null, primary key
#  title       :string
#  status      :string           default("active")
#  genre       :string
#  artist_id   :bigint(8)
#  source_id   :bigint(8)
#  source_link :string
#  views       :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  library_id  :bigint(8)
#
# Track
class Track < ApplicationRecord
  include Scopable

  belongs_to :library
  belongs_to :artist
  belongs_to :source, optional: true
  has_many :playlist_tracks, dependent: :destroy
  has_many :playlists, through: :playlist_tracks

  enum status: {
    active: 'active',
    blocked: 'blocked'
  }
  enum genre: {
    pop: 'pop',
    rock: 'rock',
    jazz: 'jazz',
    country: 'country'
  }

  validates :title, presence: true
  validates :artist, presence: true
  validates :source_link, presence: true

  before_save :set_source

  scope :title_ordered_by, ->(direction) { order(title: direction) }
  scope :updated_at_ordered_by, ->(direction) { order(updated_at: direction) }
  scope :views_ordered_by, ->(direction) { order(views: direction) }
  scope :popularity, -> { views_ordered_by(:desc) }
  scope :title_like, ->(str) { where('lower(title) like ?', "%#{str.downcase}%") }
  scope :recent, -> { updated_at_ordered_by(:desc) }
  scope :previous_tracks, ->(date) { where('created_at < ?', date).order(created_at: :desc) }
  scope :next_tracks, ->(date) { where('created_at > ?', date).order(:created_at) }
  scope :tracks_for_user, ->(user_id) { where(library_id: Library.where(user_id: user_id).try(:pluck, :id)) }

  delegate :user, to: :library

  private

  def set_source
    uri = URI.parse(source_link)
    self.source = Source.find_by(domain: uri.host)
  end
end

app/controllers/tracks_controller.rb
# frozen_string_literal: true

# TracksController
class TracksController < ApplicationController
  before_action :set_track, only: %i[show edit update destroy play_previous play_next]
  before_action :set_library, :set_playlist
  load_and_authorize_resource

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.accessible_by(current_ability).scoped(search_params).page(params[:page])
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track.increment!(:views)
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit; end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  # TODO: N+1 issue: https://github.com/flyerhzm/bullet/issues/147
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def play_previous
    previous_track = Track.accessible_by(current_ability)
                          .previous_tracks(@track.created_at)
                          .first
    if previous_track.present?
      redirect_to track_path(previous_track)
    else
      flash[:notice] = 'No previous track found'
      render :show
    end
  end

  def play_next
    next_track = Track.accessible_by(current_ability)
                      .next_tracks(@track.created_at)
                      .first
    if next_track.present?
      redirect_to track_path(next_track)
    else
      flash[:notice] = 'No next track found'
      render :show
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_track
    @track = Track.find(params[:id])
  end

  def set_library
    @library = current_user.try(:library)
  end

  def set_playlist
    params[:playlist_id].present? && @playlist = Playlist.find(params[:playlist_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def track_params
    params.require(:track).permit(:title, :status, :genre, :artist_id, :source_id,
                                  :source_link, :views, :library_id,
                                  playlist_ids: [])
  end

  def search_params
    params[:q] || {}
  end
end

app/views/tracks/_form.html.erb
<% form_path = @playlist.present? ? [@playlist, @track] : @track %>
<%= simple_form_for(form_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <%= f.input :library_id, as: :hidden, input_html: { value: @library.id } %>
  <% if params[:playlist_id].present? %>
    <%= f.association :playlists, collection: Playlist.accessible_by(current_ability).pluck(:title, :id), selected: params[:playlist_id] %>
  <% end %>
  <%= f.input :title %>
    <div class="input-group">
      <div class="input-group-prepend">
        <button type="button" class="btn btn-outline-secondary form-control" data-toggle="modal" data-target="#addArtistModal" data-target-input="">Add</button>
      </div>
      <%= f.association :artist, as: :string, label: false, readonly: true,
        input_html: {value: f.object.artist.try(:fullname), class: "artist-fullname-input"} %>
      <%= f.hidden_field :artist_id, value: f.object.artist_id, class: "artist-id-input" %>
    </div>
    <%= f.input :genre, collection: Track::genres.values, prompt: "Select Genre" %>
    <%= f.input :source_link %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%= render partial: 'artists/artist_fields_modal' %>

app/views/tracks/_list.html.erb
<div class="d-inline-block"><h2>Tracks</h2></div>
<div class="d-inline-block float-right">
  <div class="dropdown dropleft">
    <button class="btn dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort By</button>
    <div class="dropdown-menu" aria-labelledby="sortDropdown">
      <%= link_to "Title", tracks_path("q[title_ordered_by]": "asc"), class: "dropdown-item" %>
      <%= link_to "Recently added", tracks_path("q[updated_at_ordered_by]": "desc"), 
      class: "dropdown-item" %>
      <%= link_to "Popular", tracks_path("q[views_ordered_by]": "desc"), class: "dropdown-item" %>
    </div>
  </div>
</div>
<div id="paginator">
  <%= render partial: 'tracks/pagination', locals: { tracks: tracks } %>
</div>
<% if tracks.present? %>
<ul class="list-unstyled" id="tracks">
  <%= render tracks %>
</ul>
<% else %>
<div> 0 tracks found</div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <span class="pull-right"><%= link_to 'New Track', new_track_path %></span>
  </div>
</div>

  

app/views/tracks/_pagination.html.erb
<%= paginate tracks, 
  theme: 'twitter-bootstrap-4', 
  pagination_class: "justify-content-center",
  remote: true 
%>

app/views/tracks/_track.html.erb
<li class="media">
  <%= link_to(track_path(track), class: "list-group-item list-group-item-action") do %>
  <%= fa_icon "music 2x", class: "float-left mr-3" %>
  <div class="media-body">
    <span class="mt-0 mb-1"><%= track.title %></span>
    <% if track.genre.present? %>
      <span class="badge badge-info"><i><%= track.genre.camelcase %></span></i></span>
    <% end %>
  </div>
  <% end %>

  <div class="pull-right ml-3">
    <div class="dropdown dropleft">
      <button class="btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= fa_icon "ellipsis-v" %></button>
      <div class="dropdown-menu">
        <%= link_to "Edit Track", edit_track_path(track), class: "dropdown-item" %>
        <%= link_to 'Remove from Library', track, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</li>

app/views/tracks/_track_fields.html.erb
<div class="nested-fields border border-warning">
  <div class="row">
    <div class="col-md-6">
      <legend class="legend">Track</legend>
    </div>
    <div class="col-md-6">
      <span class="pull-right text-danger">
        <%=fa_icon "minus-circle"%>&nbsp;<%= link_to_remove_association "remove", f %>
      </span>
    </div>
  </div>
  <%= f.input :library_id, as: :hidden, input_html: { value: @library.id } %>
  <%= f.input :title %>
  <div class="input-group">
    <div class="input-group-prepend">
      <button type="button" class="btn btn-outline-secondary form-control" data-toggle="modal" data-target="#addArtistModal" data-target-input="">Add</button>
    </div>
    <%= f.association :artist, as: :string, label: false, readonly: true,
      input_html: {value: f.object.artist.try(:fullname), class: "artist-fullname-input"} %>
    <%= f.hidden_field :artist_id, value: f.object.artist_id, class: "artist-id-input" %>
  </div>
  <%= f.input :genre, collection: Track::genres.values, prompt: "Select Genre" %>
  <%= f.input :source_link %>
</div>

app/views/tracks/edit.html.erb
<div class="card my-3">
  <div class="card-header">
    <h1>Editing Track</h1>
  </div>
  <div class="card-body">
    <%= render 'form', track: @track %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @track %> |
    <%= link_to 'Back', tracks_path %>
  </div>
</div>

app/views/tracks/index.html.erb
<div class="my-3 p-3 bg-white rounded box-shadow">
  <%= render partial: 'list', locals: { tracks: @tracks } %>
</div>

app/views/tracks/index.js.erb
$("#tracks").html("<%= j render(@tracks) %>");
$("#paginator").html("<%= j render(partial: 'pagination', locals: { tracks: @tracks }) %>");

app/views/tracks/new.html.erb
<div class="card my-3">
  <div class="card-header">
    <h1>New Track</h1>
  </div>
  <div class="card-body">
    <%= render 'form', track: @track %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', tracks_path %>
  </div>
</div>

app/views/tracks/show.html.erb
<div class="card text-center">
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="<%= @track.source_link %>"></iframe>
  </div>
  <div class="card-body">
    <h3 class="card-title"><%= @track.title %></h3>
    <p class="card-text">
      <span>By <%= @track.artist.fullname %></span>
      <span class="mb-2 text-muted"><i><%= "- (#{@track.genre})" %></i></span>
    </p>
  </div>
  <div class="card-footer text-muted">
    <%= link_to play_previous_track_path(@track) do %>
      <%= fa_icon "arrow-left 3x", class: "pull-left ml-3" %>
    <% end %>
    <%= link_to 'Edit', edit_track_path(@track) %> | <%= link_to 'Back', tracks_path %>
    <%= link_to play_next_track_path(@track) do %>
      <%= fa_icon "arrow-right 3x", class: "pull-right mr-3" %>
    <% end %>
  </div>
</div>