config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :sources
  resources :libraries
  resources :playlists do
    resources :playlist_tracks
    resources :tracks, only: [:new, :create]
  end
  resources :playlist_tracks
  resources :tracks do 
    member do
      get 'play_previous'
      get 'play_next'
    end
  end
  root 'home#index'
  get 'search_type', to: 'home#search_type', as: :search_type
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/inbox"
end

app/models/playlist_track.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: playlist_tracks
#
#  id          :bigint(8)        not null, primary key
#  playlist_id :bigint(8)
#  track_id    :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# PlaylistTrack
class PlaylistTrack < ApplicationRecord
  include Scopable
  belongs_to :playlist, inverse_of: :playlist_tracks
  belongs_to :track, inverse_of: :playlist_tracks

  validates :playlist_id, presence: true
  validates :track_id, presence: true

  scope :title_ordered_by, ->(direction) { joins(:track).merge(Track.title_ordered_by(direction)) }
  scope :updated_at_ordered_by, ->(direction) { joins(:track).merge(Track.updated_at_ordered_by(direction)) }
  scope :views_ordered_by, ->(direction) { joins(:track).merge(Track.views_ordered_by(direction)) }
  scope :popularity, -> { views_ordered_by(:desc) }
  scope :title_like, ->(str) { joins(:track).merge(Track.title_like(str)) }
  scope :playlist_tracks_for_user, ->(user_id) { where(playlist_id: Playlist.playlists_for_user(user_id).try(:pluck, :id)) }
  scope :recent, -> { updated_at_ordered_by(:desc) }
  scope :within_playlist, ->(playlist_id) { joins(:playlist).merge(Playlist.where(id: playlist_id)) }
end

app/controllers/playlist_tracks_controller.rb
# frozen_string_literal: true

# PlaylistTracksController
class PlaylistTracksController < ApplicationController
  before_action :set_playlist_track, only: %i[show edit update destroy]
  before_action :set_playlist
  load_and_authorize_resource

  # GET /playlist_tracks
  # GET /playlist_tracks.json
  def index
    @playlist_tracks = PlaylistTrack.accessible_by(current_ability).scoped(search_params)
    if params[:playlist_id].present?
      @playlist_tracks = @playlist_tracks.within_playlist(params[:playlist_id])
    end
    @playlist_tracks = @playlist_tracks.page(params[:page])
  end

  # GET /playlist_tracks/1
  # GET /playlist_tracks/1.json
  def show; end

  # GET /playlist_tracks/new
  def new
    @playlist_track = PlaylistTrack.new
  end

  # GET /playlist_tracks/1/edit
  def edit; end

  # POST /playlist_tracks
  # POST /playlist_tracks.json
  def create
    @playlist_track = PlaylistTrack.new(playlist_track_params)
    respond_to do |format|
      if @playlist_track.save
        format.html { redirect_to @playlist_track, notice: 'Playlist track was successfully created.' }
        format.json { render :show, status: :created, location: @playlist_track }
      else
        format.html { render :new }
        format.json { render json: @playlist_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlist_tracks/1
  # PATCH/PUT /playlist_tracks/1.json
  def update
    respond_to do |format|
      if @playlist_track.update(playlist_track_params)
        format.html { redirect_to @playlist_track, notice: 'Playlist track was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist_track }
      else
        format.html { render :edit }
        format.json { render json: @playlist_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlist_tracks/1
  # DELETE /playlist_tracks/1.json
  def destroy
    @playlist_track.destroy
    # respond_to do |format|
    #   format.html { redirect_to playlist_tracks_url, notice: 'Playlist track was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    redirect_back(fallback_location: root_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist_track
    @playlist_track = PlaylistTrack.find(params[:id])
  end

  def set_playlist
    @playlist = Playlist.find(params[:playlist_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playlist_track_params
    params.require(:playlist_track).permit(:playlist_id, :track_id)
  end

  def search_params
    params[:q] || {}
  end
end

app/views/playlist_tracks/_form.html.erb
<%= simple_form_for(@playlist_track) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :playlist %>
    <%= f.association :track %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/playlist_tracks/_list.html.erb
<div class="d-inline-block"><h2>Playlist Tracks</h2></div>
<div class="d-inline-block float-right">
  <div class="dropdown dropleft">
    <button class="btn dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort By</button>
    <div class="dropdown-menu" aria-labelledby="sortDropdown">
      <%= link_to "Title", playlist_playlist_tracks_path(playlist_tracks.first.try(:playlist_id), "q[title_ordered_by]": "asc"), class: "dropdown-item", remote: true %>
      <%= link_to "Recently added", playlist_playlist_tracks_path(playlist_tracks.first.try(:playlist_id), "q[updated_at_ordered_by]": "desc"), 
      class: "dropdown-item", remote: true %>
      <%= link_to "Popular", playlist_playlist_tracks_path(playlist_tracks.first.try(:playlist_id), "q[views_ordered_by]": "desc"), class: "dropdown-item", remote: true %>
    </div>
  </div>
</div>
<div id="paginator">
  <%= render partial: 'playlist_tracks/pagination', locals: { playlist_tracks: playlist_tracks } %>
</div>
<% if playlist_tracks.present? %>
<ul class="list-unstyled" id="playlist_tracks">
  <%= render playlist_tracks %>
</ul>
<% else %>
<div> 0 tracks found</div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <span class="pull-right"><%= link_to 'Add To Playlist', new_playlist_track_path(playlist_tracks.first.try(:playlist_id)) %></span>
  </div>
</div>

app/views/playlist_tracks/_pagination.html.erb
<%= paginate playlist_tracks,
  theme: 'twitter-bootstrap-4', 
  pagination_class: "justify-content-center",
  remote: true 
%>

app/views/playlist_tracks/_playlist_track.html.erb
<% track = playlist_track.track %>
<li class="media">
  <%= link_to(track_path(track), class: "list-group-item list-group-item-action") do %>
  <%= fa_icon "music 2x", class: "float-left mr-3" %>
  <div class="media-body">
    <span class="mt-0 mb-1"><%= track.title %></span>
    <% if track.genre.present? %>
      <span class="badge badge-info"><i><%= track.genre.camelcase %></span></i></span>
    <% end %>
  </div>
  <% end %>

  <div class="pull-right ml-3">
    <div class="dropdown dropleft">
      <button class="btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= fa_icon "ellipsis-v" %></button>
      <div class="dropdown-menu">
        <%= link_to "Edit Track", edit_track_path(track), class: "dropdown-item" %>
        <%= link_to 'Remove from Playlist', playlist_playlist_track_path(playlist_track.playlist_id, playlist_track.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</li>

app/views/playlist_tracks/edit.html.erb
<h1>Editing Playlist Track</h1>

<%= render 'form', playlist_track: @playlist_track %>

<%= link_to 'Show', @playlist_track %> |
<%= link_to 'Back', playlist_tracks_path %>

app/views/playlist_tracks/index.html.erb
<h1>Playlist Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Playlist</th>
      <th>Track</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlist_tracks.each do |playlist_track| %>
      <tr>
        <td><%= playlist_track.playlist %></td>
        <td><%= playlist_track.track %></td>
        <td><%= link_to 'Show', playlist_track %></td>
        <td><%= link_to 'Edit', edit_playlist_track_path(playlist_track) %></td>
        <td><%= link_to 'Destroy', playlist_track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist Track', new_playlist_track_path %>

app/views/playlist_tracks/index.js.erb
$("#playlist_tracks").html("<%= j render(@playlist_tracks.includes(:track)) %>");
$("#paginator").html("<%= j render(partial: 'playlist_tracks/pagination', locals: { playlist_tracks: @playlist_tracks.includes(:track) }) %>");

app/views/playlist_tracks/new.html.erb
<h1>New Playlist Track</h1>

<%= render 'form', playlist_track: @playlist_track %>

<%= link_to 'Back', playlist_tracks_path %>

app/views/playlist_tracks/show.html.erb
<p>
  <strong>Playlist:</strong>
  <%= @playlist_track.playlist %>
</p>

<p>
  <strong>Track:</strong>
  <%= @playlist_track.track %>
</p>

<%= link_to 'Edit', edit_playlist_track_path(@playlist_track) %> |
<%= link_to 'Back', playlist_tracks_path %>