config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :sources
  resources :libraries
  resources :playlists do
    resources :playlist_tracks
    resources :tracks, only: [:new, :create]
  end
  resources :playlist_tracks
  resources :tracks do 
    member do
      get 'play_previous'
      get 'play_next'
    end
  end
  root 'home#index'
  get 'search_type', to: 'home#search_type', as: :search_type
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/inbox"
end

app/models/library.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: libraries
#
#  id         :bigint(8)        not null, primary key
#  user_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Library
class Library < ApplicationRecord
  belongs_to :user
  has_many :playlists
  has_many :tracks
end

app/controllers/libraries_controller.rb
# frozen_string_literal: true

# LibrariesController
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    @recent_playlists = @library.playlists.recent.limit(5).page(0)
    @recent_tracks    = @library.tracks.recent.limit(5).page(0)
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit; end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_library
    @library = Library.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def library_params
    params.require(:library).permit(:user_id)
  end
end

app/views/libraries/_form.html.erb
<%= simple_form_for(@library) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/libraries/_playlists.html.erb
<%= render partial: 'playlists/list', locals: { playlists: playlists } %>

app/views/libraries/_tracks.html.erb
<%= render partial: 'tracks/list', locals: { tracks: tracks } %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.user %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<div class="card">
  <div class="card-header">
    <h2>Recent Activity</h2>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="playlists-tab" data-toggle="tab" href="#playlists" role="tab" aria-controls="playlists" aria-selected="true">Playlists</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="tracks-tab" data-toggle="tab" href="#tracks" role="tab" aria-controls="tracks" aria-selected="false">Tracks</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="popular-tab" data-toggle="tab" href="#popular" role="tab" aria-controls="popular" aria-selected="false">Popular</a>
      </li>
    </ul>
  </div>
  <div class="tab-content card-body" id="myTabContent">
    <div class="tab-pane fade show active" id="playlists" role="tabpanel" aria-labelledby="playlists-tab">
      <%= render partial: 'playlists', locals: { playlists: @recent_playlists } %>
    </div>
    <div class="tab-pane fade" id="tracks" role="tabpanel" aria-labelledby="tracks-tab">
      <%= render partial: 'tracks', locals: { tracks: @recent_tracks } %>
    </div>
    <div class="tab-pane fade" id="popular" role="tabpanel" aria-labelledby="popular-tab">
      #TODO:    
    </div>
  </div>
</div>