config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :sources
  resources :libraries
  resources :playlists do
    resources :playlist_tracks
    resources :tracks, only: [:new, :create]
  end
  resources :playlist_tracks
  resources :tracks do 
    member do
      get 'play_previous'
      get 'play_next'
    end
  end
  root 'home#index'
  get 'search_type', to: 'home#search_type', as: :search_type
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/inbox"
end

app/models/playlist.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: playlists
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  status     :string           default("active")
#  views      :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  library_id :bigint(8)
#
# Playlist
class Playlist < ApplicationRecord
  include Scopable

  belongs_to :library
  has_many :playlist_tracks, dependent: :destroy
  has_many :tracks, through: :playlist_tracks

  accepts_nested_attributes_for :tracks, reject_if: :all_blank

  enum status: {
    active: 'active',
    blocked: 'blocked'
  }

  validates :title, presence: true

  scope :title_ordered_by, ->(direction) { order(title: direction) }
  scope :updated_at_ordered_by, ->(direction) { order(updated_at: direction) }
  scope :title_like, ->(str) { where('lower(title) like ?', "%#{str.downcase}%") }
  scope :recent, -> { updated_at_ordered_by(:desc) }
  scope :playlists_for_user, ->(user_id) { where(library_id: Library.where(user_id: user_id).try(:pluck, :id)) }

  delegate :user, to: :library
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

# PlaylistsController
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[show edit update destroy]
  before_action :set_library
  load_and_authorize_resource

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.accessible_by(current_ability)
                         .includes(:tracks)
                         .scoped(search_params)
                         .page(params[:page])
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show; end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
    @playlist.tracks.build
  end

  # GET /playlists/1/edit
  def edit; end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def set_library
    @library = current_user.try(:library)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playlist_params
    params.require(:playlist).permit(
      :title, :status, :views, :library_id,
      tracks_attributes: [:id, :title, :artist_id, :genre, :source_link, :library_id]
    )
  end

  def search_params
    params[:q] || {}
  end
end

app/views/playlists/_form.html.erb
<%= simple_form_for(@playlist) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :library_id, as: :hidden, input_html: { value: @library.id } %>
    <%= f.input :title %>
    <div class="links">
      <%= f.simple_fields_for :tracks do |track| %>
        <%= render 'track_fields', f: track %>
      <% end %>
      <span class="text-success">
        <%=fa_icon "plus-circle"%>&nbsp;<%= link_to_add_association "add", f, :tracks %>
      </span>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
<%= render partial: 'artists/artist_fields_modal' %>

app/views/playlists/_list.html.erb
<div class="d-inline-block"><h2>Playlists</h2></div>
<div class="d-inline-block float-right">
  <div class="dropdown dropleft">
    <button class="btn dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort By</button>
    <div class="dropdown-menu" aria-labelledby="sortDropdown">
      <%= link_to "Title", playlists_path("q[title_ordered_by]": "asc"), class: "dropdown-item" %>
      <%= link_to "Recently added", playlists_path("q[updated_at_ordered_by]": "desc"), 
      class: "dropdown-item" %>
    </div>
  </div>
</div>
<div id="paginator">
  <%= render partial: 'playlists/pagination', locals: { playlists: playlists } %>
</div>
<% if playlists.present? %>
<div class="list-group" id="playlists">
  <%= render playlists %>
</div>
<% else %>
<div> 0 playlists found</div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <span class="pull-right"><%= link_to 'New Playlist', new_playlist_path %></span>
  </div>
</div>

app/views/playlists/_pagination.html.erb
<%= paginate playlists, 
  theme: 'twitter-bootstrap-4', 
  pagination_class: "justify-content-center",
  remote: true 
%>

app/views/playlists/_playlist.html.erb
<%= link_to(playlist_path(playlist), class: "list-group-item list-group-item-action") do %>
  <li class="media">
    <%= fa_icon "list 2x", class: "pull-right mr-3" %>
    <div class="media-body">
      <span class="mt-0 mb-1"><%= playlist.title %></span>
      <span class="float-right badge badge-info"><i><%= playlist.tracks.length %> tracks</span></i></span>
    </div>
  </li>
<% end %>

app/views/playlists/_track_fields.html.erb
<%= render partial: 'tracks/track_fields', locals: { f: f } %>

app/views/playlists/edit.html.erb
<div class="card my-3">
  <div class="card-header">
  <h1>Editing Playlist</h1>
  </div>
  <div class="card-body">
  <%= render 'form', playlist: @playlist %>
  </div>
  <div class="card-footer">
  <%= link_to 'Show', @playlist %> | 
  <%= link_to 'Back', playlists_path %>
  </div>
</div>

app/views/playlists/index.html.erb
<p id="notice"><%# notice %></p>
<div class="my-3 p-3 bg-white rounded box-shadow">
  <%= render partial: 'list', locals: { playlists: @playlists } %>
</div>

app/views/playlists/index.js.erb
$("#playlists").html("<%= j render(@playlists) %>");
$("#paginator").html("<%= j render(partial: 'pagination', locals: { playlists: @playlists }) %>");

app/views/playlists/new.html.erb
<div class="card my-3">
  <div class="card-header">
    <h1>New Playlist</h1>
  </div>
  <div class="card-body">
    <%= render 'form', playlist: @playlist %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', playlists_path %>
  </div>
</div>

app/views/playlists/show.html.erb
<div class="my-3 p-3 bg-white rounded box-shadow">
<h2><%= @playlist.title %></h2>
<%= render partial: 'playlist_tracks/list', locals: { playlist_tracks: @playlist.playlist_tracks.includes(:track).page } %>
<div>
<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>
</div>